name: restaurant_booking
description: Restaurant Booking App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.2
  fl_chart: ^0.69.0
  table_calendar: ^3.1.3
  intl: ^0.19.0
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - .env
